# Generated by Django 5.0.1 on 2024-01-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("surname", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
                ("country", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=200)),
                ("user", models.CharField(default="user", max_length=200)),
                ("gender", models.CharField(max_length=30)),
                ("date_of_birth", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
