# Generated by Django 5.0.1 on 2024-05-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_progress_count_user_search_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="payment_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="payment_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="payment_status_detail",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
