# Generated by Django 5.0.1 on 2024-05-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_progress_count_user_search_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.CharField(max_length=100, unique=True)),
                ("status", models.CharField(max_length=20)),
                (
                    "status_detail",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
    ]
