# Generated by Django 5.0.1 on 2024-05-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_paymentstatus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentStatus",
        ),
        migrations.AddField(
            model_name="user",
            name="payment_id",
            field=models.CharField(default="", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="status_detail",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
