# Generated by Django 5.0.1 on 2024-05-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_payment_id_user_payment_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="payment_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="user",
            name="payment_status_detail",
        ),
    ]
