# Generated by Django 5.0.1 on 2024-05-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_delete_paymentstatus_user_payment_id_user_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="payment_id",
            field=models.CharField(
                default="default_payment_id", max_length=100, unique=True
            ),
        ),
    ]
