version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    container_name: lexcom_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: lexcom_db
      POSTGRES_USER: lexcom
      POSTGRES_PASSWORD: lexcom
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local